In [1]:
import numpy as np

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.3.0'

In [4]:
a = tf.constant(1.0)
b = tf.constant(2.0)
c = a + b
c

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [5]:
c.numpy()

3.0

In [6]:
rank_1_tensor = tf.constant([1., 2., 3.])
rank_1_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [7]:
rank_2_tensor = tf.constant([[1., 2., 3.],
                             [4., 5., 6.]], dtype=float)
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [9]:
rank_3_tensor = tf.constant(np.random.random([4, 5, 6]))
rank_2_tensor = tf.constant(np.random.random([4, 4]))

In [10]:
var_x = tf.Variable(tf.constant([[1], [2], [3]]))
var_x.shape

TensorShape([3, 1])

In [11]:
tf.reshape(var_x, [1, 3])

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [12]:
tf.argmax(var_x)

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([2])>