In [1]:
import tensorflow as tf
import tensorflow.keras

from tensorflow.keras import layers, losses, optimizers, Sequential

In [2]:
x = tf.range(10)
print(x)
x = tf.random.shuffle(x)
net = layers.Embedding(10,4)
out = net(x)
print(out)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[ 0.03482603 -0.03197817 -0.01530094  0.0476951 ]
 [-0.02601637  0.04675907 -0.03088318  0.01866532]
 [-0.02318355  0.03795299  0.04055852  0.01197658]
 [ 0.01851684 -0.02938117 -0.02994657  0.04311985]
 [-0.0212698   0.01545134  0.00206415 -0.00722749]
 [ 0.04096618  0.03300068  0.04420466  0.02338122]
 [-0.02917941 -0.02275266  0.03522915 -0.04593877]
 [ 0.03672196  0.01744754  0.04838767  0.00731013]
 [ 0.03615047 -0.01593577  0.03365907  0.0152669 ]
 [ 0.01987157 -0.01301886  0.02645913  0.04009027]], shape=(10, 4), dtype=float32)


In [3]:
net.embeddings

<tf.Variable 'embedding/embeddings:0' shape=(10, 4) dtype=float32, numpy=
array([[-0.02917941, -0.02275266,  0.03522915, -0.04593877],
       [ 0.04096618,  0.03300068,  0.04420466,  0.02338122],
       [ 0.03672196,  0.01744754,  0.04838767,  0.00731013],
       [ 0.01851684, -0.02938117, -0.02994657,  0.04311985],
       [-0.02601637,  0.04675907, -0.03088318,  0.01866532],
       [ 0.03482603, -0.03197817, -0.01530094,  0.0476951 ],
       [-0.02318355,  0.03795299,  0.04055852,  0.01197658],
       [ 0.01987157, -0.01301886,  0.02645913,  0.04009027],
       [-0.0212698 ,  0.01545134,  0.00206415, -0.00722749],
       [ 0.03615047, -0.01593577,  0.03365907,  0.0152669 ]],
      dtype=float32)>

In [4]:
cell = layers.SimpleRNNCell(3)
cell.build(input_shape = (None,4))
cell.trainable_variables

[<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.171893  , -0.64852244,  0.57171607],
        [ 0.4939884 , -0.05699605, -0.75201803],
        [ 0.43041778,  0.14538538,  0.06341827],
        [ 0.28989935,  0.40283763, -0.4997841 ]], dtype=float32)>,
 <tf.Variable 'recurrent_kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[ 0.21136546,  0.94367784,  0.25455195],
        [ 0.9734269 , -0.17976123, -0.14186592],
        [-0.08811715,  0.2777733 , -0.95659673]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]