In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10,activation='softmax')
])

In [4]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [5]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 890us/step - loss: 1.5812 - accuracy: 0.8981
Epoch 2/5
1875/1875 [==============================] - 2s 897us/step - loss: 1.5226 - accuracy: 0.9445
Epoch 3/5
1875/1875 [==============================] - 2s 863us/step - loss: 1.5091 - accuracy: 0.9563
Epoch 4/5
1875/1875 [==============================] - 2s 810us/step - loss: 1.5016 - accuracy: 0.9632
Epoch 5/5
1875/1875 [==============================] - 2s 905us/step - loss: 1.4969 - accuracy: 0.9669


In [6]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 1.4944 - accuracy: 0.9680


[1.4943747520446777, 0.9679999947547913]

In [7]:
model(x_train[:1]).numpy()

array([[3.0286992e-11, 4.9344383e-15, 1.4916227e-10, 5.8193301e-04,
        4.8021508e-28, 9.9941814e-01, 2.2044518e-16, 3.4469093e-15,
        1.4657351e-14, 4.3419082e-13]], dtype=float32)

In [8]:
model.predict(x_train[:1])

array([[3.0286992e-11, 4.9344383e-15, 1.4916227e-10, 5.8193301e-04,
        4.8021508e-28, 9.9941814e-01, 2.2044518e-16, 3.4469093e-15,
        1.4657351e-14, 4.3419082e-13]], dtype=float32)

In [9]:
class Cat():
    def __inti__(self):
        pass
    def speak(self):
        print("I'm a cat.")
        
class Blackcat(Cat):
    def speak(self):
        print("I'm a black cat.")
        
cat = Blackcat()
cat.speak()
super(Blackcat, cat).speak()

I'm a black cat.
I'm a cat.


In [10]:
import numpy as np
a = tf.constant(np.random.rand(4,))
b = tf.constant(np.random.rand(4,1))
print(a,b)

tf.Tensor([0.09832661 0.28986484 0.22925596 0.69229396], shape=(4,), dtype=float64) tf.Tensor(
[[0.77411072]
 [0.71968523]
 [0.57123012]
 [0.22089048]], shape=(4, 1), dtype=float64)
