In [1]:
import numpy as np

In [2]:
c = np.array([[1, 2, 3], 
              [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
d = np.array(((1, 2, 3), 
              (4, 5, 6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
g = np.array([['a', 'b', 'c'], 
              ['d', 'e', 'f']])
g

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [5]:
e = np.array([(1, 2, 3), 
              (4, 5, 6),
              (7, 8, 9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
f = np.array([[1, 2, 3], 
              [4, 5, 6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

算数

In [7]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [8]:
a + 4

array([4, 5, 6, 7])

In [9]:
a * 2

array([0, 2, 4, 6])

In [10]:
b = np.arange(4, 8)

In [11]:
a - b

array([-4, -4, -4, -4])

In [12]:
a + b

array([ 4,  6,  8, 10])

In [13]:
a * b

array([ 0,  5, 12, 21])

In [14]:
a @ b

38

In [15]:
A = np.arange(0, 9).reshape(3,3)

In [16]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
B = np.ones((3, 3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [19]:
C = np.zeros((3, 3))
C

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.dot(A, B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

数组变形

In [21]:
a = np.random.random(12)

In [22]:
A = a.reshape(3, 4)
A

array([[0.60575307, 0.7252799 , 0.43462312, 0.76651939],
       [0.70792315, 0.57375256, 0.13570932, 0.61507806],
       [0.96528213, 0.28131442, 0.86315197, 0.51959179]])

In [23]:
A.T

array([[0.60575307, 0.70792315, 0.96528213],
       [0.7252799 , 0.57375256, 0.28131442],
       [0.43462312, 0.13570932, 0.86315197],
       [0.76651939, 0.61507806, 0.51959179]])

In [24]:
A.ravel()

array([0.60575307, 0.7252799 , 0.43462312, 0.76651939, 0.70792315,
       0.57375256, 0.13570932, 0.61507806, 0.96528213, 0.28131442,
       0.86315197, 0.51959179])

In [26]:
from scipy import linalg

In [29]:
a = np.random.random(16)
A = a.reshape(4, 4)
linalg.inv(A)

array([[ 2.31927892, -2.34643974,  0.8535509 , -0.05336195],
       [-3.50761642,  2.57482667, -0.86741732,  2.05692908],
       [-1.73244702,  0.17284555,  2.19714899, -0.77396264],
       [ 2.10803187,  0.16518187, -0.36875994, -1.54465904]])

In [30]:
A

array([[0.74570215, 0.62485174, 0.08516226, 0.76364503],
       [0.60023302, 0.85430776, 0.2689335 , 0.98214321],
       [0.8503499 , 0.69925257, 0.50936486, 0.64655514],
       [0.87885838, 0.77717294, 0.02338014, 0.34544625]])

激活函数

In [31]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [32]:
sigmoid(np.array([1, 2, 3, 4, 5]))

array([0.73105858, 0.88079708, 0.95257413, 0.98201379, 0.99330715])

In [35]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [36]:
tanh(np.array([1,2,3,4,5]))

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ])

In [39]:
def relu(x):
    return np.maximum(x,0)

In [40]:
relu(np.array([1,-1]))

array([1, 0])

人工神经元

In [46]:
def neural_unit(inputs, weights, activate='relu'):
    ipt = np.sum(inputs * weights)
    if activate == 'relu':
        return relu(ipt)
    if activate == 'sigmoid':
        return sigmoid(ipt)

In [43]:
neural_unit(np.array([1,0,1]), np.array([-0.21, 0.3, 0.7]))

0.49

In [47]:
neural_unit(np.array([1,0,1]), np.array([-0.21, 0.3, 0.7]), activate='sigmoid')

0.6201064323430902

布尔运算

In [52]:
def AND(x1: float, x2: float):
    weight = np.array([20, 20, -30])
    inputs = np.array([x1, x2, 1.])
    
    return sigmoid(np.dot(weight, inputs))

In [55]:
AND(1, 1)

0.9999546021312976

In [56]:
def OR(x1: float, x2: float):
    weight = np.array([20, 20, -10])
    inputs = np.array([x1, x2, 1.])
    
    return sigmoid(np.dot(weight, inputs))

In [58]:
OR(0, 1)

0.9999546021312976

In [70]:
def NAND(x1: float, x2: float):
    weight = np.array([-20, -20, 30])
    inputs = np.array([x1, x2, 1.])
    
    return sigmoid(np.dot(weight, inputs))

In [71]:
NAND(0, 0)

0.9999999999999065

In [74]:
def XOR(x1: float, x2: float):  
    y1 = OR(x1, x2)
    y2 = NAND(x1, x2)
    
    return AND(y1, y2)

In [75]:
XOR(0,1)

0.999954519621495

softmax

In [76]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

In [78]:
softmax(np.arange(1, 10))

array([2.12078996e-04, 5.76490482e-04, 1.56706360e-03, 4.25972051e-03,
       1.15791209e-02, 3.14753138e-02, 8.55587737e-02, 2.32572860e-01,
       6.32198578e-01])

In [79]:
def logit(x):
    return np.log(x / (1-x))

In [80]:
logit(0.9)

2.1972245773362196