In [1]:
import tensorflow as tf
import tensorflow.keras as keras

In [2]:
layer = keras.layers.Dense(3,activation = 'relu')
layer_config = layer.get_config()
layer_config

{'name': 'dense',
 'trainable': True,
 'dtype': 'float32',
 'units': 3,
 'activation': 'relu',
 'use_bias': True,
 'kernel_initializer': {'class_name': 'GlorotUniform',
  'config': {'seed': None}},
 'bias_initializer': {'class_name': 'Zeros', 'config': {}},
 'kernel_regularizer': None,
 'bias_regularizer': None,
 'activity_regularizer': None,
 'kernel_constraint': None,
 'bias_constraint': None}

In [3]:
A = tf.constant([[2,2,2,2],[4,4,4,4],[8,8,8,8]])
kernal = tf.constant([[1,1],[2,2]])
A = tf.reshape(A,[1,3,4,1])
A
kernal = tf.reshape(kernal,[2,2,1,1])

In [4]:
kernal

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[1]],

        [[1]]],


       [[[2]],

        [[2]]]], dtype=int32)>

In [5]:
out = tf.nn.conv2d(A,kernal,strides = 1,padding=[[0,0],[0,0],[0,0],[0,0]])
out

<tf.Tensor: shape=(1, 2, 3, 1), dtype=int32, numpy=
array([[[[20],
         [20],
         [20]],

        [[40],
         [40],
         [40]]]], dtype=int32)>

In [6]:
fashion_minist = keras.datasets.fashion_mnist